### ISSUE TITLE
[Vraag] vehicle.first_admission_netherlands returnt een string met Python code, hoe te gebruiken

### ISSUE THREAD

**Issue by Calimerorulez** [frenck/python-vehicle#26]
Beste Franck,

Ik wil je eigenlijk niet lastigvallen met deze basic/noob-vragen, maar ik probeer het toch. Ik heb deze module ontdekt, wil hem graag gebruiken, en ik zie dat `vehicle.first_admission_netherlands` bijvoorbeeld een `datetime.date(2019, 8, 28)` als string teruggeeft.

Nu heb ik me werkelijk een breuk geGoogled, maar hoe kom ik van die sting naar een functie/object whatever, zodat ik er een echte datumstring van maken kan? Als ik hem namelijk print, dan print ie gewoon `datetime.date(2019, 8, 28)`. Ik wil de output van het script dat ik aan het maken ben in een YAML proppen, maar dan maakt ie er gewoon `'datum_eerste_toelating' : datetime.date(2019, 8, 28)`

Sorry voor de vraag, ik hoop dat je me een juiste kant op wil wijzen. Dank!

**Comment by Calimerorulez** [comment]
Uiteindelijk gevonden

**Comment by frenck** [comment]
Great!

If you need additional info, don't hesitate to ask 👍
