### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by joostlek** [frenck/python-vehicle#376]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Empty issue.

**Comment by joostlek** [comment]
Misclicked the enter button lmao

**Comment by frenck** [comment]
Don't worry, stuff happens 👍 

../Frenck
